#!/usr/bin/env bash
# First-time CABLED bootstrap of the dock body (ESP32). docs/OTA.md §0.1.
#
# This is the ONE unavoidable USB step: a chip with no OTA partitions can't
# receive its first OTA, and the partition table that ENABLES OTA ships in this
# flash. After this runs once, every future update is network OTA (build &
# announce from the console) — no cable.
#
# Steps: ensure secrets.h → flash over USB (pio run -t upload) → confirm the
# body joins Wi-Fi and dials the station.
#
# Env: STATION_URL, DOCK_NAME override the secrets.h values if creating it fresh.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
FW_DIR="$ROOT/node-dock/body-firmware/dock_body_v0"
SECRETS="$FW_DIR/include/secrets.h"
EXAMPLE="$FW_DIR/include/secrets.h.example"
PIO="${PIO:-$HOME/.platformio/penv/bin/pio}"

echo "== bootstrap: dock body (ESP32) — CABLED first flash =="
echo "firmware: $FW_DIR"
command -v "$PIO" >/dev/null || { echo "!! pio not found at $PIO (set PIO=...)" >&2; exit 2; }

# 1. secrets.h — create from prompts/env if missing (never overwrite).
if [[ ! -f "$SECRETS" ]]; then
  echo "== secrets.h missing — creating it =="
  SSID="${WIFI_SSID:-}"; PASS="${WIFI_PASSWORD:-}"
  [[ -z "$SSID" ]] && read -r -p "2.4GHz Wi-Fi SSID: " SSID
  [[ -z "$PASS" ]] && { read -r -s -p "Wi-Fi password: " PASS; echo; }
  STA="${STATION_URL:-}"; DOCK="${DOCK_NAME:-anne-bot}"
  [[ -z "$STA" ]] && read -r -p "Station WS URL (e.g. ws://192.168.1.17:8099/ws, blank = standalone): " STA
  cat > "$SECRETS" <<EOF
// Generated by bootstrap-body.sh. Gitignored — real Wi-Fi creds, never commit.
#pragma once
#define WIFI_SSID     "$SSID"
#define WIFI_PASSWORD "$PASS"
#define STATION_URL   "$STA"
#define DOCK_NAME     "$DOCK"
EOF
  echo "wrote $SECRETS (SSID=$SSID, dock=$DOCK, station=${STA:-<standalone>})"
else
  echo "secrets.h exists — using it (delete it to re-enter)."
fi

# 2. Flash over USB. The OTA partition table (partitions.csv) + rollback flags
#    are baked into the build config — this first flash is what makes the chip
#    OTA-capable.
echo "== pio run -t upload (USB) =="
( cd "$FW_DIR" && "$PIO" run -t upload )

# 3. Verify: the body should boot, join Wi-Fi, and (if STATION_URL set) dial the
#    station. We can't reliably TTY the serial monitor from a script, so confirm
#    via the station roster if a station URL is configured.
STA_LINE="$(grep -E '#define STATION_URL' "$SECRETS" | sed -E 's/.*"([^"]*)".*/\1/')"
if [[ -z "$STA_LINE" ]]; then
  echo "== done. STATION_URL is empty (standalone body) — nothing to verify via station. =="
  echo "   Watch the boot log with:  cd $FW_DIR && $PIO device monitor"
  exit 0
fi
# Derive the REST base from the WS URL: ws://host:port/ws → http://host:port
API_BASE="$(sed -E 's#^ws(s?)://([^/]+)/ws$#http\1://\2#' <<<"$STA_LINE")"
echo "== verifying the body dials the station ($API_BASE) =="
echo "   (boots + joins Wi-Fi + connects; give it ~20s)"
ok=0
for i in $(seq 1 20); do
  sleep 2
  if curl -fsS "$API_BASE/api/ota" 2>/dev/null | grep -q '"role": *"firmware"\|firmware'; then
    if curl -fsS "$API_BASE/api/docks" 2>/dev/null | grep -q '"firmware"'; then ok=1; break; fi
  fi
done
if [[ "$ok" == 1 ]]; then
  echo "== ✓ body is online at the station. Future updates are network OTA. =="
  curl -fsS "$API_BASE/api/docks" 2>/dev/null | python3 -m json.tool 2>/dev/null || true
else
  echo "!! body not seen at the station within 40s." >&2
  echo "   Check: station running at $API_BASE? correct Wi-Fi SSID (2.4GHz)? STATION_URL reachable from the body's network?" >&2
  echo "   Watch the serial log:  cd $FW_DIR && $PIO device monitor" >&2
  exit 1
fi
